version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-go-banking
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./bank-api.sql:/docker-entrypoint-initdb.d/bank-api.sql

  app:
    build: .
    container_name: go-banking-api
    restart: always
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  db_data:
